### ISSUE TITLE
Code Improvements recommendations

### ISSUE THREAD

**Issue by pbruna** [gperdomor/sanitize#2]
## Protocol name
I think a better name will be `Modelizable`, because what its doing it's returning a Model object.

## `Pre` and `Post` validations
- Almost all other libraries implement this as `beforeFilter` and `afterFilter`, and I think those names are clearer.
- Also, if you already have the `data` JSON, it becomes unnecessary to pass it as a parameter.

So the code will look like this:

```swift
    static func beforeFilter() throws {
        guard this.data["name"]?.string != nil else {
        .....
    }

    static func afterFilter() throws {
        .....
    }
```

## Class declaration
The following code reduces duplication:

```swift
class TestModel: Sanitizable { // or struct
   objectKeys([
      objectKey("name", type: String, required: true),
      objectKey("email", type: String, required: true),
      objectKey("id", type: Node)
   ])
    //...
}
```

**Comment by gperdomor** [comment]
Since the `preSanitize`function is static, and called before initialization, I need pass the parameter...

I will put the `pre` and `post` recommendations in a new #4 issue targeted to 2.0 milestone :D
